---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: cleanup
spec:
  workspaces:
    # Shared workspace where data stored
    - name: source
  params:
    - name: filename
      type: string
  steps:
    - name: check-dir-exist
      image: ubuntu
      script: |
        if [ ! -f "$(workspaces.source.path)/$(params.filename)" ]; then
          echo "Something went wrong and could not find data source under $(workspaces.source.path)/$(params.filename)"
          exit 1
        fi
    - name: cleanup-workspace
      image: ubuntu
      script: |
        rm -rf $(workspaces.source.path)/$(params.filename)
    - name: verify-dir-has-gone
      image: ubuntu
      script: |
        if [ -f "$(workspaces.source.path)/$(params.filename)" ]; then
          echo "Something went wrong cleaning up and the data source still exists under $(workspaces.source.path)/$(params.filename)"
          exit 1
        fi
